"""Initial canonical data model

Revision ID: 367c6cdfc4fe
Revises:
Create Date: 2026-08-26 11:02:20.845450

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "367c6cdfc4fe"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baskets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("dataset_name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "geography",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "basket_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("basket_id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["basket_id"],
            ["baskets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("basket_id", "item_id", name="uq_basket_item"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_observations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("geography_id", sa.String(), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=True),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id",
            "reference_date",
            "geography_id",
            name="uq_raw_obs_source_date_geo",
        ),
    )
    op.create_table(
        "normalized_incomes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("income_basis", sa.String(), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("geography_id", sa.String(), nullable=False),
        sa.Column("income_brl", sa.Numeric(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SOURCE_VERIFIED",
                "NORMALIZED",
                "ESTIMATED",
                "MISSING",
                name="observationstatus",
            ),
            nullable=False,
        ),
        sa.Column("raw_observation_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["geography_id"],
            ["geography.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_observation_id"],
            ["raw_observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "income_basis",
            "reference_date",
            "geography_id",
            name="uq_norm_income_basis_date_geo",
        ),
    )
    op.create_table(
        "normalized_prices",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("geography_id", sa.String(), nullable=False),
        sa.Column("price_brl", sa.Numeric(), nullable=True),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SOURCE_VERIFIED",
                "NORMALIZED",
                "ESTIMATED",
                "MISSING",
                name="observationstatus",
            ),
            nullable=False,
        ),
        sa.Column("raw_observation_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["geography_id"],
            ["geography.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_observation_id"],
            ["raw_observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "item_id",
            "reference_date",
            "geography_id",
            name="uq_norm_price_item_date_geo",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("normalized_prices")
    op.drop_table("normalized_incomes")
    op.drop_table("raw_observations")
    op.drop_table("ingestion_runs")
    op.drop_table("basket_items")
    op.drop_table("geography")
    op.drop_table("data_sources")
    op.drop_table("baskets")
    # ### end Alembic commands ###
