"""add_performance_indexes

Revision ID: a1bd726d913b
Revises: 367c6cdfc4fe
Create Date: 2026-09-08 11:15:54.218738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bd726d913b'
down_revision: Union[str, Sequence[str], None] = '367c6cdfc4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_norm_income_geo_basis_date', 'normalized_incomes', ['geography_id', 'income_basis', 'reference_date'], unique=False)
    op.create_index('ix_norm_price_geo_item_date', 'normalized_prices', ['geography_id', 'item_id', 'reference_date'], unique=False)
    op.create_index('ix_raw_obs_source_geo_date', 'raw_observations', ['source_id', 'geography_id', 'reference_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_obs_source_geo_date', table_name='raw_observations')
    op.drop_index('ix_norm_price_geo_item_date', table_name='normalized_prices')
    op.drop_index('ix_norm_income_geo_basis_date', table_name='normalized_incomes')
    # ### end Alembic commands ###
